### ISSUE TITLE
GTK Apps Graphical Issue (Glitch)

### ISSUE THREAD

**Issue by ghost** [QtCurve/qtcurve#71] opened 2014-06-21 05:49 UTC
Hi guys.

I'd just like to ask if there's any way to fix this issue. Whenever I use gtk apps (Firefox f.ex., or even xchat), the dropdown menus (if you click a menu, f.ex.) are completely flat, with no shade whatsoever (at best), but most of the time they're straight up deprecated. This issue also occurs on hovering. I'm including screenshots. 
My setup:
Slackware 14.1
KDE 4.12.5
qtcurve-gtk and qtcurve installed.

**Comment by ghost** [comment] 2014-06-21 05:49
![posnetek2](https://cloud.githubusercontent.com/assets/7442746/3347965/dc7689c4-f907-11e3-9d46-8ccebc7b239e.png)

**Comment by yuyichao** [comment] 2014-06-21 12:17
This looks like the cairo leaking issue that was fixed about one year ago.
Should be fixed by the [1.8.16 release](https://github.com/QtCurve/qtcurve/commit/b172824e16dd3ad9977671f44720be518b8da3a9) of the gtk version.

Close for now. Feel free to reopen if you can reproduce it with the newest version.

**Closed as completed by yuyichao** 2014-06-21 12:17 UTC

**Comment by yuyichao** [comment] 2014-06-21 12:20
And for some more details, this is caused by the missing flush when drawing the window shadow under kwin.

**Comment by ghost** [comment] 2014-06-22 06:26
yuyichao, thank you very much for your pointers. Indeed, i needed to use a newer version, and when i installed it, it works flawlessly.
Thank you for your help.
