### ISSUE TITLE
Issue with background and QML integration

### ISSUE THREAD

**Issue by sandsmark** [QtCurve/qtcurve#6] opened 2013-11-06 19:39 UTC
When using background pixmap/gradient/transparency, it integrates poorly with QML-based applications, ![screenshot](http://bugsfiles.kde.org/attachment.cgi?id=75802)

[Related KDE bug](https://bugs.kde.org/show_bug.cgi?id=311574)

**Comment by yuyichao** [comment] 2013-11-06 19:51
Looking at the KDE-bug thread, I'm glad you have finally find the right place to report bugs :P. (Maybe I should do a search of QtCurve on KDE-bug when I have time ...... :D )

There are some known issue with the default screen locker and QtCurve with translucency enabled but I have not yet got a time to debug it (partially because screen locker is ...err... a little harder to debug than a normal application). I'm glad that you have figured out that this may be qml related and the screen locker I am using right now as a work around is "Default Widgets", which looks fine just like the plasma desktop.

Could you please check:
1. if this is also a problem for any other QML based applications (I'm currently not aware of any)
2. if you have the same problem with the Oxygen-Transparent style and Bespin style with translucency enabled.

Thank you very much.

**Comment by sandsmark** [comment] 2013-11-06 20:05
according to Aaron it is probably related to QGraphicsProxyWidget, so I'll try to make a small test application using that. :-)

**Comment by yuyichao** [comment] 2013-12-10 16:36
I am using a completely different way to do translucent background now which should have minimum (if any) interference with the application.
Please give the current master a try. The screen locker and other apps that uses custom translucent background widget should all work now.

**Comment by yuyichao** [comment] 2013-12-10 16:56
P.S. the problem was that in order to have translucent background, the window has to be ARGB instead of RGB (which is the default). This was accomplished in QtCurve by setting Qt::WA_TranslucentBackground attribute on the widget. However, as a side effect, [this also set Qt::WA_NoSystemBackground](https://qt.gitorious.org/qt/qt/source/5a24211e0dab76b61a1631f0959274927ffe929d:src/gui/kernel/qwidget.cpp#L11003) on the widget which means [the routine provided by the style to draw the background will not be called](https://qt.gitorious.org/qt/qt/source/5a24211e0dab76b61a1631f0959274927ffe929d:src/gui/kernel/qwidget.cpp#L5575). The style therefore need to workaround this either by setting the attribute back or install a event filter for paint event on the widget. Either way, it means if the widget sets the translucent background attribute by itself the style will still draw the background.

On the transition to QML, I believe what happens is that the widget which provides the input area and sth else has no parent (as they are proxied to the visual parent) and therefore becomes a "top level window" (at least according to the window flags) which means the style will do the background attribute hack on it and draws the background for the widget.

Plasma desktop actually has the same problem by was workaround in QtCurve by blacklist. Now with the new way to get translucent background, I have already partually removed the blacklist and it still looks fine ;-P.

**Comment by sandsmark** [comment] 2013-12-11 11:23
Ah, awesome! I'm sorry I never got around to making a testcase. :-(

It seems I got a drawing error now, though, if I used the "circles" pixmap background thing that got a black background. Just disabling that everything else looked nice, though.

But I'll test a bit more when I get home.

**Comment by yuyichao** [comment] 2013-12-11 12:02
It is possible that it is caused by other refactoring that is going on. Could you please paste a config file that has the problem?

**Comment by sandsmark** [comment] 2013-12-11 19:22
The QML stuff looks nice now, here's a screenshot of the black background:

![image](https://f.cloud.github.com/assets/25765/1727095/72655704-6299-11e3-8223-489cb5267a57.png)

And here's the settings: http://iskrembilen.com/settings.qtcurve

**Comment by yuyichao** [comment] 2013-12-11 19:50
So is the black region supposed to be the same color with the part outside that pixmap?
I believe it is caused by the change in QPainter mode...

As I said, a lot of painting routines have been refactored (mainly moving from custom eventFilter to the standard virtual functions of the style) and I would probably need to do a thorough test before the next release in order to fix (or at least minimize ...) breakage.... It's very nice that you have noticed this now. I will try to fix it later. (Although in the meantime you would probably need to use a version which is less broken for you :-P )

**Comment by yuyichao** [comment] 2013-12-11 19:53
Could you please test if the following patch works around the problem for you?

```
diff --git a/qt4/style/qtcurve.cpp b/qt4/style/qtcurve.cpp
index 6f45b1c..6c7da14 100644
--- a/qt4/style/qtcurve.cpp
+++ b/qt4/style/qtcurve.cpp
@@ -11609,6 +11609,7 @@ void Style::drawBackground(QPainter *p, const QWidget *widget, BackgroundType ty
                    popupMenuCols()[ORIGINAL_SHADE], bgndRect, opacity, type,
                    BGND_MENU != type ? opts.bgndAppearance :
                    opts.menuBgndAppearance);
+    p->setCompositionMode(QPainter::CompositionMode_SourceOver);
     drawBackgroundImage(p, isWindow, imgRect);
 }
```

It's probably not the final solution but I suspect this is where the problem is.

**Comment by sandsmark** [comment] 2013-12-12 15:26
Yes, it does, awesome. :-)

**Comment by yuyichao** [comment] 2013-12-12 16:08
Good.

Close this issue for now.
I will try to find the best solution and push it later (have sth else to deal with now...). Please test that and open a new issue then if the new problem still exists.

**Closed as completed by yuyichao** 2013-12-12 16:08 UTC
Labels: bug
